**Задание 1**
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])). 



Решение 1:

In [1]:
import numpy as np

d = int(input('Введите d: '))
arr = np.arange(0, d)
reversed_arr = arr[::-1]
reversed_arr

Введите d: 5


array([4, 3, 2, 1, 0])

Решение 2:

In [2]:
d = int(input('Введите d: '))
res = [x for x in range(0, d, 1)]
res.reverse()
np.array(res)


Введите d: 5


array([4, 3, 2, 1, 0])

**Задание 2**
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.


In [3]:
def matr(s):
  arr = np.arange(0, s)  #Не совсем понял условие задачи, поэтому в случае если предполагается, что N должно входить в значения главной диагонали, то arr = np.arange(0, s+1)
  reversed_arr = arr[::-1]
  v = np.diag(reversed_arr)
  print(np.diag(reversed_arr), ',\nсумма значений главной диагонали: ', np.trace(v))

matr(int(input('\nВведите количество элементов матрицы: ')))


Введите количество элементов матрицы: 5
[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]] ,
сумма значений главной диагонали:  10


**Задание 3**
Решите систему уравнений:
4x + 2y + z = 4;
x + 3y = 102;
5y + 4z = -3.

In [4]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
from numpy import linalg
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

Проверка


In [5]:
np.allclose(np.dot(a, linalg.solve(a, b)), b)

True

**Задание 4**
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем.
На сайт заходит очередной посетитель, о покупках которого известно следующее:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats.


In [7]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
  )

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

def cosine(a, b):
    length_a = np.linalg.norm(a)
    length_b = np.linalg.norm(b)
    return np.dot(a, b) / (length_a * length_b)

proximity = []
for lines in users_stats:
  proximity.append(cosine(lines, next_user_stats))
nearest = max(proximity)
#print(nearest)
#print(proximity.index(nearest))
print('В результате сравнения с покупками нового пользователя:\n', proximity, '\ncамым похожим пользователем является пользователь с ID: ', (proximity.index(nearest)+1), '\nс соответствующими покупками', users_stats[proximity.index(nearest)])

В результате сравнения с покупками нового пользователя:
 [0.19999999999999996, 0.8451542547285165, 0.3999999999999999, 0.7905694150420948, 0.3999999999999999, 0.0, 0.0, 0.9486832980505138, 0.0, 0.0] 
cамым похожим пользователем является пользователь с ID:  8 
с соответствующими покупками [0 1 1 0 0 0]
